# File node1.toml

[parity]
chain = "/opt/parityPoA/parityGenesis.json"
base_path = "/opt/parityPoA/node1"

[network]
port = 30300
#bootnodes = []

[rpc]
disable = true

[websockets]
disable = true

[account]
#password = ["/opt/parityPoA/pwd/password.pwd"]

[mining]
#engine_signer = "0x576b4bfd1c33F978eA173265f0340309eE68D78a"
reseal_on_txs = "none"
force_sealing = true